### ISSUE TITLE
would you like please us steps how to add this to maltego 

### ISSUE THREAD

**Issue by Ahmedabdsalam** [cmlh/Maltego-Facebook#20]

**Comment by cmlh** [comment]
@Ahmedabdsalam The generic instructions for installing local transforms are maintained by [Paterva](http://dev.paterva.com/developer/getting_started/building_your_own_local_transform.php).

Unfortunately I made the deliberate decision not to create installation documentation as every Operating System is different and knowledge of Perl is/was a prerequisite rather than attempt to to provide unpaid/free support and therefore not fulfil any SLA I may have promised inadvertently.

The support will change when I transition these to remote transforms.
